In [1]:
%gui qt5
%matplotlib qt5
from functools import partial as _partial
import numpy as np
from scipy import optimize

import matplotlib.pyplot as plt
import matplotlib.gridspec as mpl_gs
import matplotlib.cm as cmap
from matplotlib import rcParams
rcParams.update(
    {'font.size': 16,'lines.linewidth': 2, 'axes.grid': True})

import pyaccel
import mathphys
from pymodels import si

# Results comparison

In [2]:
ring = si.create_accelerator()
ring.vchamber_on = True
famdata = si.get_family_data(ring)
bpms = np.array(famdata['BPM']['index']).flatten()

## Old

In [32]:
par = np.zeros((2,6))
par[0,0] = 10e-3
par[1,0] = 2e-3
out, *args = pyaccel.tracking.line_pass(ring, par, indices=np.array([1, 1000, len(ring)]))
print(out.shape)
print(out[0, :, :])
print(out[1, :, :])

(2, 6, 3)
[[ 1.00000000e-02 -2.82195125e-03             nan]
 [ 0.00000000e+00  5.10970738e-03             nan]
 [ 0.00000000e+00  0.00000000e+00             nan]
 [ 0.00000000e+00  0.00000000e+00             nan]
 [ 0.00000000e+00  0.00000000e+00             nan]
 [ 0.00000000e+00 -1.48630443e-05             nan]]
[[ 2.00000000e-03 -4.49810335e-04  1.67847519e-03]
 [ 0.00000000e+00  8.98782960e-04 -6.78624285e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.32474074e-07  6.71327513e-07]]


In [33]:
par = np.zeros((2,6))
par[0,0] = 10e-3
par[1,0] = 2e-3
par = [10e-3, 0, 0, 0, 0, 0]
out, *args = pyaccel.tracking.line_pass(ring, par, indices='closed')
print(len(ring))
print(out.shape)
print(out)

6489
(6, 6490)
[[0.01 0.01 0.01 ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]]


In [34]:
par = np.zeros((2,6))
par[0,0] = 9e-3
par[1,0] = 2e-3
out, *args = pyaccel.tracking.ring_pass(ring, par, turn_by_turn=True, nr_turns=3)
print(out.shape)
print(out[0, :, :])
print(out[1, :, :])

(2, 6, 4)
[[ 9.00000000e-03  6.34370595e-03  7.56808388e-05 -6.21499483e-03]
 [ 0.00000000e+00 -5.42108459e-04 -6.36213720e-04 -4.66923033e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.02672969e-04  6.49203783e-05  8.24489134e-06]]
[[ 2.00000000e-03  1.67847519e-03  8.08924931e-04 -3.44282492e-04]
 [ 0.00000000e+00 -6.78624285e-05 -1.11170954e-04 -1.16369995e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  6.71327513e-07 -1.70815759e-06 -6.49831325e-06]]


In [35]:
par = np.zeros((2,6))
par[0,0] = 9e-3
par[1,0] = 2e-3
out, *args = pyaccel.tracking.ring_pass(ring, par, turn_by_turn=False, nr_turns=10)
print(out.shape)
print(out)

(2, 6)
[[ 1.95488262e-03 -6.41677104e-04  0.00000000e+00  0.00000000e+00
   0.00000000e+00  3.01430765e-04]
 [ 1.80821133e-03  5.35545795e-05  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -2.08040216e-05]]


In [36]:
par = np.zeros((2,6))
par[0,0] = 9e-3
par[1,0] = 2e-3
out = pyaccel.tracking.element_pass(ring[30], par, energy=3e9, harmonic_number=1, radiation_on=False, cavity_on=False, vchamber_on=False)
print(out.shape)
print(out)

(2, 6)
[[9.00053655e-03 6.70688387e-05 0.00000000e+00 0.00000000e+00
  0.00000000e+00 5.36281721e-06]
 [2.00011635e-03 1.45435441e-05 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.19173448e-06]]


## New

In [3]:
par = np.zeros((6,2))
par[0,0] = 10e-3
par[0,1] = 2e-3
out, *args = pyaccel.tracking.line_pass(ring, par, indices=np.array([1, 1000, len(ring)]))
print(out.shape)
print(out[:, 0, :])
print(out[:, 1, :])

(6, 2, 3)
[[ 1.00000000e-02 -2.82195125e-03             nan]
 [ 0.00000000e+00  5.10970738e-03             nan]
 [ 0.00000000e+00  0.00000000e+00             nan]
 [ 0.00000000e+00  0.00000000e+00             nan]
 [ 0.00000000e+00  0.00000000e+00             nan]
 [ 0.00000000e+00 -1.48630443e-05             nan]]
[[ 2.00000000e-03 -4.49810335e-04  1.67847519e-03]
 [ 0.00000000e+00  8.98782960e-04 -6.78624285e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.32474074e-07  6.71327513e-07]]


In [4]:
par = np.zeros((6,2))
par[0,0] = 10e-3
par[0,1] = 2e-3
par = [10e-3, 0, 0, 0, 0, 0]
out, *args = pyaccel.tracking.line_pass(ring, par, indices='closed')
print(len(ring))
print(out.shape)
print(out)

6489
(6, 6490)
[[0.01 0.01 0.01 ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]
 [0.   0.   0.   ...  nan  nan  nan]]


In [5]:
par = np.zeros((6,2))
par[0,0] = 9e-3
par[0,1] = 2e-3
out, *args = pyaccel.tracking.ring_pass(ring, par, turn_by_turn=True, nr_turns=3)
print(out.shape)
print(out[:, 0, :])
print(out[:, 1, :])

(6, 2, 4)
[[ 9.00000000e-03  6.34370595e-03  7.56808388e-05 -6.21499483e-03]
 [ 0.00000000e+00 -5.42108459e-04 -6.36213720e-04 -4.66923033e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.02672969e-04  6.49203783e-05  8.24489134e-06]]
[[ 2.00000000e-03  1.67847519e-03  8.08924931e-04 -3.44282492e-04]
 [ 0.00000000e+00 -6.78624285e-05 -1.11170954e-04 -1.16369995e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  6.71327513e-07 -1.70815759e-06 -6.49831325e-06]]


In [6]:
par = np.zeros((6,2))
par[0,0] = 9e-3
par[0,1] = 2e-3
out, *args = pyaccel.tracking.ring_pass(ring, par, turn_by_turn=False, nr_turns=10)
print(out.shape)
print(out)

(6, 2, 11)
[[[ 1.95488262e-03  1.80821133e-03  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[-6.41677104e-04  5.35545795e-05  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

In [ ]:
par = np.zeros((6,2))
par[0,0] = 9e-3
par[0,1] = 2e-3
out = pyaccel.tracking.element_pass(ring[30], par, energy=3e9)
print(out.shape)
print(out)

# Speed Comparison

In [2]:
ring = si.create_accelerator()
ring.vchamber_on = True
famdata = si.get_family_data(ring)
bpms = np.array(famdata['BPM']['index']).flatten()
twi, *_ = pyaccel.optics.calc_twiss(ring)

In [3]:
bun = pyaccel.tracking.generate_bunch(250e-12, 2.5e-12, 8e-4, 2.5e-3, twi[0], 1000, cutoff=6)

## New Code

In [8]:
%%time
out, *args = pyaccel.tracking.line_pass(ring, bun, indices='closed')

CPU times: user 1.88 s, sys: 161 ms, total: 2.04 s
Wall time: 2.03 s


In [9]:
%%time
out, *args = pyaccel.tracking.line_pass(ring, bun, indices=bpms)

CPU times: user 1.72 s, sys: 25 ms, total: 1.74 s
Wall time: 1.74 s


In [10]:
%%time
out, *args = pyaccel.tracking.line_pass(ring, bun, indices=None)

CPU times: user 1.73 s, sys: 302 µs, total: 1.73 s
Wall time: 1.72 s


## Old Code

In [4]:
%%time
out, *args = pyaccel.tracking.line_pass(ring, bun, indices='closed')

CPU times: user 27.2 s, sys: 119 ms, total: 27.3 s
Wall time: 27.2 s


In [5]:
%%time
out, *args = pyaccel.tracking.line_pass(ring, bun, indices=bpms)

CPU times: user 2.61 s, sys: 48.8 ms, total: 2.65 s
Wall time: 2.59 s


In [6]:
%%time
out, *args = pyaccel.tracking.line_pass(ring, bun, indices=None)

CPU times: user 1.83 s, sys: 8.23 ms, total: 1.83 s
Wall time: 1.81 s
